<?php

/*
Plugin Name: WordPress Nav Menu Widget Extension
Plugin URI: https://github.com/mcguffin/wp-nav-menu-widget-extension/
Description: Adds another option "Pages" to the default WP Nav Menu Widget. Use this for a site tree navigation.
Author: Jörn Lund
Version: 0.0.1
Author URI: https://github.com/mcguffin/
*/


class WPNavMenuWidgetExtended {

	private static $_instance = null;
	
	public static function instance() {
		if ( is_null( self::$_instance ) )
			self::$_instance = new self();
		return self::$_instance;
	}
	
	private function __construct() {	
		add_action( 'widgets_init' , array( &$this , 'wpnav_menu_extend' ) , 99 );
		add_action( 'wp_head' , array( &$this , 'wpnav_print_navmenu_css' ) , 99 );
		add_action( 'init' , array(&$this,'plugins_loaded') );
	}
	function plugins_loaded() {
		load_plugin_textdomain('wp-nav-menu-extension',false,dirname( plugin_basename( __FILE__ )) . '/languages/');
	}
	function wpnav_menu_extend() {
		require_once(  plugin_dir_path( __FILE__ ) . 'include/class-wp-nav-menu-widget-extended.php' );
		unregister_widget('WP_Nav_Menu_Widget');
		register_widget('WP_Nav_Menu_Widget_Extended');
	}
	function init_theme_css( $force = false ) {
		$theme_slug = strtolower(get_stylesheet());
		$opt_name = "navmenu_widget_css_{$theme_slug}";
		
		if ( false === ( $wpnav_css = get_option($opt_name) ) || $force ) {
			$wpnav_css = $this->read_theme_css();
			$wpnav_css = apply_filters("navmenu_widget_css_{$theme_slug}" , $wpnav_css );
			$wpnav_css = update_option($opt_name,$wpnav_css);
		}
		return $wpnav_css;
	}
	function read_theme_css() {
		$theme_slug = strtolower(get_stylesheet());
		$cssfile = get_stylesheet_directory() . '/style.css';
		$css = file_get_contents($cssfile);
		preg_match( '/\.(current_page_item|current-menu-item)([^{]*){(.*)}/imsU' , $css , $matches );
		if ( isset($matches[3]) ) {
			$wpnav_css = sprintf(".widget_nav_menu .current_page_item > a,
.widget_nav_menu .current-menu-item > a {%s}
",
					$matches[3]);
			
		}
		return $wpnav_css;
	}

	function wpnav_print_navmenu_css() {
		$css = $this->init_theme_css();
		printf( '<style id="wp-nav-menu-widget-extended" type="text/css" media="screen">
		/* Generated by plugin WordPress Nav Menu Widget Extension */
		%s
		</style>' , $css );
	}

}
WPNavMenuWidgetExtended::instance();

