<?php

/*
Plugin Name: WP Sub Menu Widget
Plugin URI: https://github.com/mcguffin/wp-sub-menu-widget/
Description: Widget showing submenu of the currently selected manu item.
Author: Jörn Lund
Version: 0.0.1
Author URI: https://github.com/mcguffin/
*/


class SubMenuWidget {

	private static $_instance = null;
	
	public static function instance() {
		if ( is_null( self::$_instance ) )
			self::$_instance = new self();
		return self::$_instance;
	}
	
	private function __construct() {	
		add_action( 'widgets_init' , array( &$this , 'load_sub_menu_widget' ) , 99 );
		add_action( 'wp_head' , array( &$this , 'print_submenu_css' ) , 99 );
		add_action( 'init' , array(&$this,'plugins_loaded') );
	}
	function plugins_loaded() {
		load_plugin_textdomain('wp-sub-menu-widget',false,dirname( plugin_basename( __FILE__ )) . '/languages/');
	}
	function load_sub_menu_widget() {
		require_once(  plugin_dir_path( __FILE__ ) . 'include/class-sub-menu-widget.php' );
		require_once(  plugin_dir_path( __FILE__ ) . 'include/class-walker-sub-menu.php' );
		require_once(  plugin_dir_path( __FILE__ ) . 'include/class-walker-sub-menu-page.php' );
		register_widget('Sub_Menu_Widget');
	}
	function init_theme_css( $force = false ) {
		$theme_slug = strtolower(get_stylesheet());
		$opt_name = "submenu_widget_css_{$theme_slug}";
		
		if ( false === ( $wpsub_css = get_option($opt_name) ) || $force ) {
			$wpsub_css = $this->read_theme_css();
			$wpsub_css = apply_filters("submenu_widget_css_{$theme_slug}" , $wpsub_css );
			$wpsub_css = update_option($opt_name,$wpsub_css);
		}
		return $wpsub_css;
	}
	function read_theme_css() {
		$theme_slug = strtolower(get_stylesheet());
		$cssfile = get_stylesheet_directory() . '/style.css';
		$css = file_get_contents($cssfile);
		preg_match( '/\.(current_page_item|current-menu-item)([^{]*){(.*)}/imsU' , $css , $matches );
		if ( isset($matches[3]) ) {
			$wpsub_css = sprintf(".widget_sub_menu .current_page_item > a,
.widget_sub_menu .current-menu-item > a {%s}
",
					$matches[3]);
			
		}
		return $wpsub_css;
	}

	function print_submenu_css() {
		$css = $this->init_theme_css();
		printf( '<style id="sub-menu-widget" type="text/css" media="screen">
		/* Generated by plugin Sub Menu Widget */
		%s
		</style>' , $css );
	}

}
SubMenuWidget::instance();

